@startuml

hide footbox
!pragma teoz true

title QoS 1 : At Least Once

participant Sender as S
participant Receiver as R

activate S
S -> S : Store msg
S -> R : <b>1</b> PUBLISH(QoS=1,DUP=0)
deactivate S
activate R
R -> R : Apply msg
R -> S : <b>2</b> PUBBACK
deactivate R
activate S
S -> S : Discard msg
||10||
deactivate S


@enduml