@startuml

hide footbox
!pragma teoz true

title QoS 0 : At Most Once

participant Sender as S
participant Receiver as R


S -> R : <b>1</b> PUBLISH(QoS=0,DUP=0)
activate R
R -> R : Apply msg
||10||
deactivate R

@enduml