@startuml
title Hermes (golang)

interface Transport{

}

interface Node{
    DoStep(msg raftpb.Message)
}

interface Pod{
    GetID() int64
    AddNode() error
    RemoveNode() error

}

class pod{
    - id int64
    - transport Transport

}


abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml